Add volume for object storage
uniuuu/zotprime pull request #47
Opened 2024-12-09 14:51 UTC by MarkOWiesemann

It makes sense to persistently store the minio data in production environments so that in case of a reboot you do not need to fix some sync issues because the minio storage is not initialized and filled anymore.

Similiar to the db data i used the local driver.

2024-12-12 13:20 UTC, uniuuu commented
Hi @MarkOWiesemann 
The `gateway: 10.5.5.1` is made with purpose to facilitate setup when both client and server are on the same computer installed and calls 127.0.0.1 as the server IP address.

2024-12-12 13:21 UTC, uniuuu requested changes
miniodata can be volume but no need to remove `gateway: 10.5.5.1`

2024-12-12 13:48 UTC, MarkOWiesemann commented
Hi i don't know why it says it changed but the gateway is still in there. Maybe a line break?

2024-12-13 18:19 UTC, uniuuu commented
Hi @MarkOWiesemann 
Gotcha it's line break. Thank you.

2024-12-13 18:20 UTC, uniuuu commented
Anyway I'll have to add it to development branch first.

2024-12-13 18:23 UTC, uniuuu commented
@MarkOWiesemann For production use, please consider Kubernetes instead of docker compose, i.e. MicroK8s based which is already included into this repository. It already uses `kind: PersistentVolumeClaim` https://github.com/uniuuu/zotprime/blob/development/zotprime-k8s/microk8s/manifests/zotprime-minio.yaml

2024-12-15 02:12 UTC, uniuuu commented
Hi @MarkOWiesemann 
Merged it in https://github.com/uniuuu/zotprime/releases/tag/v2.9.0

2024-12-15 02:12 UTC, closed without merging